language: android

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - tools
     - tools
     - platform-tools
     - build-tools-25.1.3
     - android-25
     - add-on
     - extra-android-m2repository
     - extra-google-m2repository

script:
  - ./gradlew build connectedCheck

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"